### ISSUE TITLE
Can I have operators as array of objects instead of array of strings?

### ISSUE THREAD

**Issue by paritosh64ce** [zebzhao/Angular-QueryBuilder#129]
As of now, the `queryBuilder` supports `operators` like - array of string values.

    notes: {name: 'Notes', type: 'textarea', operators: ['=', '!=']}

What I expect `operators` to be is array of name-value pairs.

        notes: {
            name: 'Notes', type: 'textarea',
            operators: [
                  { name: 'Equals To', value: '=' },
                  { name: 'Doesn't Equals To', value: '!=' }
            ]
       }

This can also be useful for localization. Is it possible?

**Comment by vanilsonbr** [comment]
The lib doesn't support operators being objects instead of strings now, although there is a PR related to it (#147).

I think that the best way to implement this is to create a enum or union type containing your operators and then create a mapping object to retrieve their literal names.

Something like that:
```typescript
type QueryOperators = "Equals" | "NotEquals" | "GreaterThan" | "GreaterThanEquals" | "LowerThan" | "LowerThanEquals" | ... ;

export class QueryComponent {
    // ...

    queryOperatorsLiteralNames: { [key in QueryOperators] : string } = {
        "Equals" : "Equals to",
        "NotEquals" : "Not equals to",
        "GreaterThan" : "Greater than",
        "GreaterThanEquals" : "Greater than or equals to",
        "LowerThan" : "Lower than or equals to",
        "LowerThanEquals" : "Lower than",
        // ...
    } 
}
```

then on the .html, you wanna make use of `queryOperatorsLiteralNames`:
```html
<ng-container *queryOperator="let rule; let operators=operators;">
    <select [(ngModel)]="rule.operator">
        <option *ngFor="let operator of operators" [value]="operator">{{queryOperatorsLiteralNames[operator]}}</option>
    </select>
</ng-container>
```

Hope it helps!

**Comment by paritosh64ce** [comment]
After logging the issue I ended up doing the same.
