### ISSUE TITLE
Custom styling not applied in rulesets

### ISSUE THREAD

**Issue by arsx** [zebzhao/Angular-QueryBuilder#13]
Hello @zebzhao 

Thank you for the great component.
When I add a new ruleset at the 2nd level (and further), custom (Material) elements are not being applied.
In your example (https://zebzhao.github.io/Angular-QueryBuilder/demo/), if you click on the add ruleset button on the second level, the new ruleset will appear with default styling:
![image](https://user-images.githubusercontent.com/155003/36053714-62db13f4-0db8-11e8-8a0c-fd19021c7b45.png)

Is this a known issue or something that would be addressed soon?

Thank you

**Comment by zebzhao** [comment]
This is a pretty serious bug. I will fix this as soon as I can. It looks like I didn't test it well enough for the latest release.

**Comment by zebzhao** [comment]
This issue should be now fixed in 0.2.2 release.

**Comment by arsx** [comment]
Thanks!
