### ISSUE TITLE
Angular 9 app fails to load

### ISSUE THREAD

**Issue by AccessViolator** [zebzhao/Angular-QueryBuilder#132]
0.6.0 and Angular 9.0.7 ng serve'd app fails to load (partial callstack):
```
core.js:6185 ERROR Error: Uncaught (in promise): TypeError: Cannot read property 'type' of undefined
TypeError: Cannot read property 'type' of undefined
    at Module.ɵɵNgOnChangesFeature (core.js:26816)
    at query-builder.component.js:1284
    at Module../node_modules/angular2-query-builder/dist/angular2-query-builder/esm5/lib/query-builder/query-builder.component.js (query-builder.component.js:1313)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/angular2-query-builder/dist/angular2-query-builder/esm5/public-api.js (public-api.js:1)
    at __webpack_require__ (bootstrap:84)
    at Module../node_modules/angular2-query-builder/dist/angular2-query-builder/esm5/angular2-query-builder.js (angular2-query-builder.js:1)
    at __webpack_require__ (bootstrap:84)
```
[This](https://github.com/angular/angular/issues/36042) suggest that rebuilding the library with --prod and latest Angular may solve the problem.

**Comment by rkramakrishna17** [comment]
Issue still occurring with changes mentioned in the link.

**Comment by AccessViolator** [comment]
I tried rebuilding with --prod (but without upgrading angular, because `npx @angular/cli update @angular/core @angular/cli` didn't work and I couldn't be bothered upgrading manually) and it solved the above error for me, though now I get a runtime error in the component itself.

OTOH copying source code to my project and including it directly works fine, so there's nothing wrong with the source code itself, but rather with how it's packaged into the library.

**Comment by phaniindra** [comment]
Any update on the issue still facing the same problem

**Comment by jmls** [comment]
ah crap - I've just hit this too ;)

**Comment by sten-dev** [comment]
Still facing same issue

**Comment by phaniindra** [comment]
Still facing the same issue updated to 0.6.1

**Comment by zhytang** [comment]
> Still facing the same issue updated to 0.6.1

I've fixed it, you will wait for the next release. @zebzhao

**Comment by phaniindra** [comment]
> > Still facing the same issue updated to 0.6.1
> 
> I've fixed it, you will wait for the next release. @zebzhao

When can we expect this release for the issue to be resolved.

Thanks.

**Comment by zebzhao** [comment]
Does 0.6.2 work for you?

**Comment by Keyzmo** [comment]
0.6.2 with angular 9.1.7 works for me, so closing.

ngcc still logs some errors when it runs, so looks like the library is not fully ng 9 compatible yet

**Comment by Keyzmo** [comment]
BTW, when source code is included directly into ng 9 project it works fine with Ivy, so again, the problem is with how it's packaged into the library
