### ISSUE TITLE
Issue in dynamically/ programmatically update of the data/options for grouped fields in angular query builder 0.5.0 (angular 8)

### ISSUE THREAD

**Issue by joshigauravv** [zebzhao/Angular-QueryBuilder#135]
**Bug**
The rule inside a a grroup/ruleset is not getting updated on programatically value set and involving the "changeField" function on query builde rinstance.

			// Assign the data to fields, refresh config object which is ound to queryBuilder
			this.fields[key].options = newOptions.sort((a, b) => (a.value > b.value) ? 1 : -1);
			this.config = {
				fields: this.fields
			};
			this.refreshField(fieldName);
			  
			private refreshField(field: string): void {
				// get the current rules with matching fields
				const srcRule = this.extractRule(field, this.queryBuilder.data.rules);

				srcRule.forEach(rule => {
				  const value = rule ? rule.value : undefined;
				  this.queryBuilder.changeField(field, rule);
				  rule.value = value;
				});
			}
	
	I used the stackoverflow as a reference to call "changeField".
	https://stackoverflow.com/questions/53312918/change-the-config-in-angular2-query-builder-dynamically
	
	
			  
The solution works if the rule 2 is same level as rule 1

### Case A)
And
	rule 1
	rule 2 (data is driven by selection from rule 1 input)

	
Solution does not work if rule is added in the group/ruleset in below fashion
### Case B)
And
	rule 1
	And
		rule 2 (data is driven from selection of rule 1 input)*
		rule 3 (data is driven from selection of rule 1 and rule 2 input)

I'm talking about this case where it does not update. Any way I cant go to rule 3 unless rule 2 shows right data.

**What is the expected behavior?**
I should be able to refresh data for rule 2 in above scenario.
In case B, I should be able to see updated data. The data is updated on openedChange event of mat-select by calling some APIs

**What is the current behavior?**
Case A works and refreshes the data when Rule 1 and rule 2 are on same initial level. 
I suspect there is some context issue happening and and "getInputContext" is unable to return the right value of key "rule"
This can be visited on QueryBuilderComponent (query-builder.component.ts)

**What are the steps to reproduce?**
1. While supplying the config object, I'm not setting up the options for any rule except the first mandatory rule
2. I add immediate Ruleset/group follwed by second rule
3. The second rule (which is in fact is an immediate rule after mandatory first rule inside a group), an API call is made for some calculation for forming the options for rule 2
4. On openedChage event of mat-select, I am attching the data in fields, assigning the fields to config and forcefully calling the changeField described in the bug section
5. When I change the data from rule 1, another call goes to change the options for rule 2
6. WHen I again open the rule, I see stale data
7. If I change the rule/field and come back to original field, I see refreshed data

**What is the use-case or motivation for changing an existing behavior?**

**Which versions of Angular, Material, OS, TypeScript, browsers are affected?**
		"@angular/core": "~8.2.14",
        "@angular/forms": "~8.2.14",
        "@angular/http": "^7.2.15",
        "@angular/material": "~8.2.3",
		"angular2-query-builder": "^0.5.0",

**Is there anything else we should know?**
I am suspecting the issue with context of rule, I unsuccessfully debugged and spent lot of time. I think this may help to zero-in on the fix

**Comment by maiona** [comment]
Is there any updates on this issue?
I'm having a similar problem cascading filters to inner rulesets. It works fine on the same level though.

**Comment by joshigauravv** [comment]
The issue can be addressed by defining the Map data structure in TS and instead of using the "options" from config, the map structure can store the dynamically changing inputs for the rules.

Appropriate values for corresponding keys (can be a combination of rule + group id) can feed to these rules as input.

**Comment by westoncraig** [comment]
I am hitting the same issue but struggling to understand what you implemented to work around it. Could you provide an example of the code (TS) and HTML structure changes required. Appreciate the help.

**Comment by TriVectorX** [comment]
> I am hitting the same issue but struggling to understand what you implemented to work around it. Could you provide an example of the code (TS) and HTML structure changes required. Appreciate the help.

In case if you are facing the similar issue, or you want to dynamically load the selection options, please perform the following steps:
1. Remove "options: []" from the field configuration, e.g.:
`_countries_: {
        name: 'Countries',
        type: 'category',
        operators: ['in', 'not in']
      },`
2. Create a Map structure, e.g.:
`data: Map<string, any> = new Map();`
3. Set values when appropriate, e.g.:
`this.data.set("_countries_", countries);` 
4. Find the 'Multiselect' container, use the Map data instead of 'options', e.g.:
`<ng-container *queryInput="let rule; let options=data; type: 'multiselect'; let onChange=onChange">
    <mat-form-field class="input-shrinked">
      <mat-select [(ngModel)]="rule.value" multiple (ngModelChange)="onChange();filterValues(rule)" ngDefaultControl>
        <mat-option *ngFor="let opt of data.get(rule.field)" [value]="opt.value">
          {{ opt.name }}
        </mat-option>
      </mat-select>
    </mat-form-field>
  </ng-container>`
