### ISSUE TITLE
Request for ES5 target in tsconfig

### ISSUE THREAD

**Issue by arsx** [zebzhao/Angular-QueryBuilder#14]
Hello @zebzhao,

Because Uglify cannot parse ES6 it will throw a syntax error:
```
ERROR in main.xxx.bundle.js from UglifyJs
Unexpected token: name (QueryRemoveButtonDirective) [main.xxx.bundle.js:3693,6]
```

Can you please set a TypeScript to target ES5 in `tsconfig.json`, or suggest a workaround for this issue.

Thank you.

**Comment by zebzhao** [comment]
Hi, have you tried bundling the `index.umd.js` file? This should work identically to the es6 build except that it targets all platforms. It even works with SystemJS which is what the plunker uses. There shouldn't be a reason to bundle the es6 build. Let me know if this works for you.

**Comment by arsx** [comment]
Hi, I am using Webpack in my project, so it takes care of the bundling.
Do you have an example of bundling using Webpack targeting ES5?

**Comment by arsx** [comment]
Also tried using `*.umd ones. But still got same error.

**Comment by zebzhao** [comment]
Can you post your webpack config? I have tried uglifying the umd file and they uglify without any problems. Do not include the other files in the dist folder, just the umd files should work.

**Comment by arsx** [comment]
Hi @zebzhao,

I am using Angular Webpack Starter (https://github.com/gdi2290/angular-starter) and its configs.

Please take a look at
`/config/webpack.common.js` 
and 
`/config/webpack.prod.js`

I noticed there is a difference between my `tsconfig.webpack.json` (https://github.com/gdi2290/angular-starter/blob/master/tsconfig.webpack.json) and the one in your project, specifically the `target` field that I was referring to initially.

I also tried with just `umd`s but it didn't work still.

Thank you.

**Comment by devilankur18** [comment]
Any updated on this one ?

**Comment by devilankur18** [comment]
I have fixed this issue, by upgrading the webpacker, which in turn updated the uglifyjs-webpack-plugin to version "^1.1.8".

**Comment by zebzhao** [comment]
Thanks for looking into this one! I haven't had the time to look into this yet and the error didn't really make sense to me.

**Comment by arsx** [comment]
Tried with `"webpack": "3.11.0",` but still same error.

**Comment by arsx** [comment]
The problem was that I was using the webpack's uglifyjs.
After adding `"uglifyjs-webpack-plugin": "1.2.0",` it seems to build properly.
Thanks all for feedback.
