### ISSUE TITLE
Addition of success, failure messages

### ISSUE THREAD

**Issue by nrjmr432** [zebzhao/Angular-QueryBuilder#2]
Hi,
I need to add various success and failure messages to each and every rule in the interface. Is it possible

**Comment by zebzhao** [comment]
Hi, what exactly are you trying to do?

Right now, you can validate the `data` object whenever the user submits the query to handle validation on every rule or a combination of rules accordingly. If you need the validation to happen when the rule is changed immediately, there needs to be support for EventEmitters in the component, which there currently isn't.

I will get around to this in the future. Alternately, you can contribute and submit a pull request for this, and I'll be happy to merge that in.
