### ISSUE TITLE
Existing plugins?

### ISSUE THREAD

**Issue by metanav** [zebzhao/Angular-QueryBuilder#22]
How can we use existing plugins for example, https://github.com/piotch/jQuery-QueryBuilder-Elasticsearch with Angular-QueryBuilder? I want to convert rules into elasticsearch query.

**Comment by zebzhao** [comment]
Angular QueryBuilder does not use the same code as jQuery QueryBuilder. You would need to analyze the plugin to see how you can convert the format to an elasticsearch query format.

**Comment by metanav** [comment]
OK, I have figured out it. I have rewritten the plugin to make it a function.

**Comment by gpicciocchi** [comment]
Hi metanav, 
did you develop the plugin for Angular QueryBuilder?

**Comment by metanav** [comment]
@gpicciocchi I used Angular component to wrap jQuery QueryBuilder.
