### ISSUE TITLE
its still not working in ie 11

### ISSUE THREAD

**Issue by Unkindx** [zebzhao/Angular-QueryBuilder#23]
I saw your commit and tried do it on localhost, because you didnt update npm package, but problem still exists

SCRIPT1002: Syntax error
vendor.bundle.js (71,1)

**Comment by zebzhao** [comment]
I'll look into it. It's working on my version of IE11, may need a metatag to turn on Edge compatibility mode.

**Comment by Unkindx** [comment]
i was open your demo and see this meta, but in my ie its not working http://prntscr.com/inme3l
http://prntscr.com/inme8z

**Comment by Unkindx** [comment]
in edge its working, but ie needs for me(

**Comment by zebzhao** [comment]
I have released 0.2.3 targeting ES5. Can you give it a try in IE now?

**Comment by Unkindx** [comment]
yep, its work now, thanks for a quick response. Works without "meta" too
