### ISSUE TITLE
Adding new ruleset previous data got destroy

### ISSUE THREAD

**Issue by sagar08** [zebzhao/Angular-QueryBuilder#25]
Hi 
I have encountered an issue, While generating a complex query with multiple Rule/ Ruleset, When I add a new Ruleset my previous ruleset data got to flush out.
I am trying to print this selected query in textarea. The query filed only show the current ruleset data, 
How can I get a complete parent data which were selected by the user for multiple rulesets>

My simple code
```
<query-builder [(ngModel)]='query' [config]='config'>  
</query-builder>
<br>
<div class='margin30'>  
  <textarea>{{query | json}}</textarea>
</div>

```
Thanks.

**Comment by zebzhao** [comment]
My apologies, I published a buggy 0.2.3 version. Please downgrade to version 0.2.2, will release a new version shortly with this problem fixed after some more testing. Thanks.

**Comment by sagar08** [comment]
Hi ZebZhao,
Thanks for the instant reply.

I tried to downgrade by changing the version in the package.json and then run the command npm install.
but still, the issue is not get resolved.

Do I need to uninstall and then install the same
OR can you please share me the command to downgrade the same

Thanks

**Comment by zebzhao** [comment]
Please run:
`npm uninstall angular2-query-builder`
`npm install angular2-query-builder@0.2.2`

Hopefully this solves your issue. I have fixed this bug already, its currently in testing.

**Comment by sagar08** [comment]
Hey, Thanks. This resolved the issue.
Just for my curiosity one question, can this query builder will work for large data.
In my case, I have approx. more than 100 fields which mostly contains drop-down with a big list, checkbox and textbox.  
What way will you suggest for binding large data dynamically?

Also want to know, as I am using Bootstrap 4 will this UI support that too.

**Comment by zebzhao** [comment]
Was just testing Bootstrap 4, checkout the new Bootstrap demo. I just released version 0.2.4, sorry about the inconvenience. 100 fields seems like not a problem, as long as they're not all nested ;)

**Comment by sagar08** [comment]
does this new version has resolved multiple ruleset issues also?

**Comment by sagar08** [comment]
great code !!! ... exactly what I am looking for!!!!
You are genius.....  @# 🥇 
Thanks a lot!

**Comment by zebzhao** [comment]
Thanks, glad to hear!
