### ISSUE TITLE
Unable to customize multiselect operators

### ISSUE THREAD

**Issue by jgornick** [zebzhao/Angular-QueryBuilder#26]
I have a use case where I want to provide custom operators for multiselect, however, `in` and `not in` are hard coded to always be added. Is it possible to override the entire list of operators for multiselect?

It looks like the same can be said for nullable types, where `is null` and `is not null` is always added.

**Comment by zebzhao** [comment]
Hi, unfortunately, there appears to be no easy way to avoid the additional operators from being added in the current version of the library. I think when the `operators` property of `Field` is specified, no additional operators should be added to it. I'm also not sure why I coded it in such a way that even providing `getOperators` of the `QueryConfig` object does not get rid of the default operators.

For now, the most extreme way to get rid of the additional operators is to use the `*queryOperator` structural directive to prevent the operators from being shown in the HTML.

**Comment by jgornick** [comment]
Thanks for the quick response!

I've skimmed through the source and don't really see too much of a reason to concat the operators for these 2 field types. Is it as easy as moving the concat operators into the default operators dictionary?
