### ISSUE TITLE
Hide parent "Remove Ruleset" with custom input components?

### ISSUE THREAD

**Issue by unciax** [zebzhao/Angular-QueryBuilder#27]
Is any way to hide root query builder "Remove Ruleset" button with custom input components?

**Comment by arsx** [comment]
@zebzhao Looks like it's hidden by default only in the Vanilla view, but not with the Custom view, where it is causing an error (same in demo).

**Comment by zebzhao** [comment]
Looks like a bug, will have to fix that.
