### ISSUE TITLE
how can i specify themplate

### ISSUE THREAD

**Issue by MartynenkoA** [zebzhao/Angular-QueryBuilder#28]
how can i specify themplate, and do something like this http://prntscr.com/ir2mzf

**Comment by zebzhao** [comment]
I'm not sure if that level of customization is currently possible with the library. You might be able to play around with the css styles using `classNames` field to get results close to that screenshot.

**Comment by MartynenkoA** [comment]
can i override template of  selector: 'query-builder',?

**Comment by zebzhao** [comment]
Unfortunately I do not think this is possible.
