### ISSUE TITLE
Unable to customize field section with someother input type like auto complete

### ISSUE THREAD

**Issue by shivarajnaidu** [zebzhao/Angular-QueryBuilder#29]
it would be grate.. If its possible to customize type of field selection input ..

This enhancement will be useful for may devs,.. Scenario like long list of (Mybe 1000+) fields coming from API call need to select filed from 1000 of options.. means it will be cumbersome user to select filed from 1000s of fields..

**Comment by zebzhao** [comment]
Is this currently not possible with `*queryField` directive and using an autocomplete component like from the Materials library?

**Comment by shivarajnaidu** [comment]
Yeah, just found ... But bit more examples for this will be helpful.. and samples seems bit older ...
