### ISSUE TITLE
Edit appearance and function

### ISSUE THREAD

**Issue by Wealing** [zebzhao/Angular-QueryBuilder#3]
Hello, I was wondering it you could provide some guidance as to how to modify the general appearance of the plugin, and how to modify the query builder options themselves. E.g. I would be interested in writing relational database style queries.

Thank you

**Comment by Wealing** [comment]
I would also find it useful to modify the text and location of the "and" and "or" buttons.

**Comment by zebzhao** [comment]
I am looking into to this to see if it's possible. I think adding css classes to each element would help?

**Comment by Wealing** [comment]
Awesome. This is something that would be very useful. I would also like to learn how to do it myself. Do you think you could provide some sort of guide or set of examples?

Thanks

**Comment by zebzhao** [comment]
The latest release has a way to change the styling of the component, by allowing user defined css classes to be used. I added a short example of how I would add custom styling, hope it helps.

**Comment by Wealing** [comment]
Thank you, I am not an expert so it will take me some time to be able to test this.
