### ISSUE TITLE
Issue with rule types with selectable options

### ISSUE THREAD

**Issue by paul-aylett** [zebzhao/Angular-QueryBuilder#31]
When adding 'Category' type rules, in some cases the first given option appears selected in the UI, but the bound rule object does not reflect this, the object has no 'value' property. If there is only one option supplied, this option will never be bound to the rule object as it appears 'value' is only set when the field changes.

**Comment by zebzhao** [comment]
Can you provide an example when the first given option appears selected in the UI? I'm not seeing the issue in the demo. Thanks.

**Comment by paul-aylett** [comment]
Thanks for getting back quickly. 
I was unable to replicate the issue on plunker so may be something on my end causing it. Going to investigate further. 
Seems that when I change the left hand 'field' dropdown, the right hand 'value' dropdown will display either nothing, or the first option, depending on whether the user made a selection or not in the value box before changing the left hand dropdown. Very strange.

**Comment by zebzhao** [comment]
Thanks for the additional info, I will look into it. Do you have the latest version of the library? I had this issue with an earlier version. The value should always reset after changing the field dropdown.
