### ISSUE TITLE
getDefaultOperator issue

### ISSUE THREAD

**Issue by jihuiwang** [zebzhao/Angular-QueryBuilder#32]
in getDefaultOperator function of query-builder.component.ts
the const operators is not an array because it already get the first value of getOperators function,
and the return value can not get the first value any more.
there wont be wrong if the value just has one character.

`const operators = this.getOperators(field.value)[0];
      if (operators && operators.length) {
        return operators[0];
      } else {`

**Comment by zebzhao** [comment]
Thanks for reporting this bug.
