### ISSUE TITLE
logical expression

### ISSUE THREAD

**Issue by hiren-dobariya** [zebzhao/Angular-QueryBuilder#33]
Thank you for creating amazing tool. Just checking is there anyway we can show/create logical express ? like (1 || 2 || 3 && ( 5  && 6 ) ).
Also, in current structure, how can we add conditions for this "(1 & 2) || (3 & 4)" expression ?

Thank you.

**Comment by zebzhao** [comment]
Can you clarify with a more detailed example? Is what you're trying to achieve different from using And/Or?

**Comment by hiren-dobariya** [comment]
Hi, Thanks for quick response.
Let's say I  want to create rule for website analytics. 

if previous url = "www.abc.com?q=a" and current url = "www.abc.com?q=b" OR visitor stay on website more than 5 minutes and visited url history count = 3. 
So check above conditions I need to convert rule into logical expression. Even I am not getting idea how can we add rule for above case. I need your guidance if anyhow we can add this in current component. Please let me know if you need any more details.

**Comment by zebzhao** [comment]
I'm not sure I understand, do you want to create another querying language (like SQL) as a field?

If that's the case I'm not sure if that's possible. Could you not just create a previousUrl, currentUrl, and duration field and configure the component that way?

Then later convert the `ngModel` data object to a logical expression?
