### ISSUE TITLE
Is it possible to disable the whole query builder in view mode

### ISSUE THREAD

**Issue by sudhakar-sekar** [zebzhao/Angular-QueryBuilder#34]
Hi,

 I have integrated angular2-query-builder in Angular4 CLI project. I want to disable the whole query builder.
 We are not allowing to add rule/ruleset, remove rule/ruleset and changing conditions also.
 Can anyone please tell me is it possible to disable the query builder.

Thanks in advance.

**Comment by jihuiwang** [comment]
i think you can use QueryButtonGroupDirective.
you can check file **demo/esm/src/app/app.component.ts**
define queryButtonGroup and put nothing in it .
I haven't try it, hope it will work. 

`<ng-container *queryButtonGroup="let ruleset; let addRule=addRule; let addRuleSet=addRuleSet; let removeRuleSet=removeRuleSet">
      <button mat-icon-button color="primary" (click)="addRule()">
        <mat-icon>add</mat-icon></button>
      <button mat-icon-button color="primary" *ngIf="addRuleSet" (click)="addRuleSet()">
        <mat-icon>add_circle_outline</mat-icon></button>
      <button mat-icon-button color="accent" *ngIf="removeRuleSet" (click)="removeRuleSet()">
        <mat-icon>remove_circle_outline</mat-icon></button>
    </ng-container>`
