### ISSUE TITLE
dynamic QueryBuilderConfig

### ISSUE THREAD

**Issue by MartynenkoA** [zebzhao/Angular-QueryBuilder#35]
can i dynamic update QueryBuilderConfig?  ([config]='getConfig()') or mayby you have some event to update config

**Comment by MartynenkoA** [comment]
that is, when i try to add fields this.config.fields[key] = its not added

**Comment by leonardoResendeLima** [comment]
+1. Same problem. Trying to fill the config object after a http call, that will return the dinamic fields I will use on the query.

**Comment by mannava** [comment]
how to convert JSON to SQL query ??

{"condition":"and","rules":[{"field":"EI_TIMESTAMP","operator":"=","value":"2018-04-03"},{"field":"EI_TRXN_TYPE","operator":"=","value":"sap"},{"condition":"and","rules":[{"field":"DCNUMBER","operator":"=","value":"2342424"}]}]}

**Comment by vincent** [comment]
I have a similar problem when trying to change an input attribute value inside a queryInput template, the template is not updated.
It is something that should be possible ?

**Comment by shahsumit** [comment]
Do we have a solution or work around for this.

**Comment by ThakkarKhushbu** [comment]
I have similar issue , I want to change option value .How can I ?
I have tried to replace fields , but got fields undefined .

**Comment by gsoares02** [comment]
I think it has to do with the change detection in this version of angular.
Try doing an Object.assign to the binded variable otherwise the ngOnChanges won't fire and update the fields array.

**Comment by zebzhao** [comment]
If you are mutating the object, you need to do so within the lifecycle hooks provided by Angular (within an Angular event). If it doesn't work, you need to create a duplicate object to trigger change detection.
 
For more clarification, I have already removed `ChangeDetectionStrategy.OnPush` to facilitate deep object comparisons, not sure if there's anything else the library can do to better facilitate this.

**Comment by zebzhao** [comment]
Switching configs tested to be working if a new object is created. Use the Object.assign strategy above need to modify config.
