### ISSUE TITLE
How can i change button text?

### ISSUE THREAD

**Issue by kumaranpg** [zebzhao/Angular-QueryBuilder#38]
I have to customize Rule, Ruleset, X button text. I gone through template, but i don't want to change from query builder plugin. Changes should trigger from my component?

**Comment by poojan1gajera** [comment]
@kumaranpg Did you find an answer to it ?

> I have to customize Rule, Ruleset, X button text. I gone through template, but i don't want to change from query builder plugin. Changes should trigger from my component?
