### ISSUE TITLE
Forms Validation

### ISSUE THREAD

**Issue by jjoaoclaro** [zebzhao/Angular-QueryBuilder#39]
Is there a way Validate the values inserted by the user and add the form control to a form group?

**Comment by zebzhao** [comment]
In the demo code, there is an [example ](https://github.com/zebzhao/Angular-QueryBuilder/blob/master/demo/esm/src/app/app.component.ts) using `[formControl]`. There is also a property on the `config.fields[key]` called [validator](https://zebzhao.github.io/Angular-QueryBuilder/interfaces/Field.html#source) which return back an error object similar to the Validator interface provided by angular.

Sorry for the lack of examples on this, let me know if you need more info on this. Currently, the `touched` and `pristine` do not work property (looking into this), but `valid` and `invalid works`.

**Comment by jjoaoclaro** [comment]
if you could give an example of the validator would be great!

maybe an example of the config that uses all properties or something like that

**Comment by zebzhao** [comment]
Created a plunkr with validator on 'Age' field.

[https://plnkr.co/edit/mtdMcJzPZ8n35V8KQN55](https://plnkr.co/edit/mtdMcJzPZ8n35V8KQN55)

Not that familiar with how Form modules work in Angular, but it seems a ngModel change does not automatically trigger form validation. I think the form validation is currently triggered by form submit, adding a Rule Set, or programatically calling updateValueAndValidity().

If anyone knows if this behavior is inline with how ReactiveForms work in Angular 2 and/or how to change this behavior please let me know.
