### ISSUE TITLE
QueryBuilderClassNames Interface is not exported

### ISSUE THREAD

**Issue by metanav** [zebzhao/Angular-QueryBuilder#40]
I am not able to import QueryBuilderClassNames using:

```
import { QueryBuilderClassNames, QueryBuilderConfig } from 'angular2-query-builder';

```

**Comment by zebzhao** [comment]
Weird, I will look into it.

**Comment by zebzhao** [comment]
Tried with the latest 0.2.5 version, seems to be working.

**Comment by metanav** [comment]
@zebzhao It is not working in the latest version. I created a PR #54 to fix this.

**Comment by zebzhao** [comment]
Sorry, you're right. Only did the testing in the plunkr with SystemJS which was probably wrong. Lesson learned for the future...
