### ISSUE TITLE
How to create and retrieve the query generated by the query builder

### ISSUE THREAD

**Issue by shahsumit** [zebzhao/Angular-QueryBuilder#45]
Just checked the demo of query builder at https://zebzhao.github.io/Angular-QueryBuilder/demo/
I have a query as how the query gets generated in the backgroud with the various filters selected and how can we retrieve this generated query.

I need to save the generated filtered query in my DB which will further be used as where clause.

**Comment by Abdullah0991** [comment]
See the [plunker demo](https://plnkr.co/edit/fgw8tfnOJ1cI48nr3MUl?p=preview) .. although it not working but you can see the code to retrieve this generated query.
