### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by gsoares02** [zebzhao/Angular-QueryBuilder#47]
Hi zeb,
Love the library and am looking forward to use it in one of our projects.

Do you have a timeframe for a next release? Are you going to update the angular version?

Thanks

**Comment by gsoares02** [comment]
Thanks for the reply.
I'm using the latest 6.x.x. It works fine though.
I was just wondering if you were intending on updating so I wouldn't have to fork it :)

**Comment by zebzhao** [comment]
Did you need to make any changes to the library to get it to work with 6.x.x? My project is still using Angular 4.x.x, so I'm not sure if it has any compatibility issues with higher versions of Angular.

**Comment by gsoares02** [comment]
Nope. It works fine. I just had to do a shallow copy to the config fields to trigger the change detection.
Other than that it works fine.
But I only tested it for a little while.

**Comment by zebzhao** [comment]
I'm not sure I understand why you need to fork the library. Is there any changes I can make that will make it easier to use the library?

**Comment by gsoares02** [comment]
I would need to fork and update if this version didn't play well with higher versions (it does).
I really need to implement the 'between' operator with 2 inputs (for dates), not sure the current version allows for this.
