### ISSUE TITLE
Changing rule fields doesn't trigger form changed/touched

### ISSUE THREAD

**Issue by paul-aylett** [zebzhao/Angular-QueryBuilder#49]
Hi,
I'm using this in a form and it seems that changing the fields in a rule doesn't mark the form as dirty, or trigger validation. Currently the only way these seem to be triggered is by adding/removing rules.

Kind regards,
Paul

**Comment by zebzhao** [comment]
The library does not currently monitor changes on any field components, as they can be overridden. However, I believe the default components should automatically trigger validation and form state changes. Will work on this for the next release.

**Comment by zebzhao** [comment]
This behavior has been added in the latest release, 0.3.0.
