### ISSUE TITLE
Remove "+ Ruleset" button

### ISSUE THREAD

**Issue by sorcamarian** [zebzhao/Angular-QueryBuilder#5]
Is it possible to remove the button `+ Ruleset` from top-right, without `CSS`?

**Comment by zebzhao** [comment]
I will mark this as a feature request for next release.

**Comment by zebzhao** [comment]
This has been added to the latest release e017ca47c7a8261d626eb7b7c8d68d0b955c81aa under the attribute binding `allowRuleset`.

**Comment by sorcamarian** [comment]
Thank you!
