### ISSUE TITLE
Update Material examples in documentation

### ISSUE THREAD

**Issue by GianfrancoFrau** [zebzhao/Angular-QueryBuilder#50]
Any plan to update to Angular and Angular Material 6.x ?

**Comment by zebzhao** [comment]
Angular Material is not a dependency. You can use whichever version of Angular Material you like. I believe the library can work with all Angular versions 4+...

**Comment by GianfrancoFrau** [comment]
Yes you're right but using the latest version of angular material, the layout is broken.
Anyway it seems it works well with angular 6

**Comment by zebzhao** [comment]
I see, I will update the examples to Material 6 (or maybe 7...) when my schedule allows me to. Thanks.
