### ISSUE TITLE
Improve error message for undefined query object.

### ISSUE THREAD

**Issue by tosehee75** [zebzhao/Angular-QueryBuilder#52]
I copied your demo and try to make it run locally, but I run into an issue when I click on "Add rule" or "Add Rule Set".

Does it have a dependency on ionic or jquery??? I thought it doesn't have any dependency other than core angular 4 libs..

`ERROR TypeError: Cannot read property 'concat' of undefined
    at QueryBuilderComponent.push../node_modules/angular2-query-builder/dist/components/query-builder/query-builder.component.js.QueryBuilderComponent.addRule (query-builder.component.js:233)
    at Object.eval [as handleEvent] (QueryBuilderComponent.html:11)
    at handleEvent (core.js:10050)
    at callWithDebugContext (core.js:11143)
    at Object.debugHandleEvent [as handleEvent] (core.js:10846)
    at dispatchEvent (core.js:7509)
    at core.js:7953
    at HTMLButtonElement.<anonymous> (platform-browser.js:1140)
    at ZoneDelegate.push../node_modules/zone.js/dist/zone.js.ZoneDelegate.invokeTask (zone.js:421)
    at Object.onInvokeTask (core.js:3748)`

**Comment by tosehee75** [comment]
HTML

`
<div class="dialog-header">
    <h1 mat-dialog-title>Rule Condition</h1>
</div>
<div class="dialog-content dialog-content-scroll">
    <mat-dialog-content>
        <div class="row gutter">
            <div class="col-lg-12">
                <query-builder [(ngModel)]='query' [config]='config'></query-builder>
            </div>
        </div>
    </mat-dialog-content>
</div>
<div class="dialog-footer">
    <mat-dialog-actions class="action-buttons action-buttons-container">
        <div class="primary-actions">
            <button type="button" class="btn btn-secondary">Cancel</button>
            <button type="button" class="btn btn-primary">Save</button>
        </div>
    </mat-dialog-actions>
</div>
`

TS

`
    query: {
        condition: 'and',
        rules: [
            { field: 'age', operator: '<=', value: 'Bob' },
            { field: 'gender', operator: '>=', value: 'm' }
            ]
    };

    config: QueryBuilderConfig = {
        fields: {
            age: {name: 'Age', type: 'number'},
            gender: {
                name: 'Gender',
                type: 'category',
                options: [
                    {name: 'Male', value: 'm'},
                    {name: 'Female', value: 'f'}
                ]
            }
        }
    };
`

**Comment by tosehee75** [comment]
`            this.query = {
                condition: "",
                rules: []
            }
`
Above fixes the problem at constructor. I guess you must define "rules" and "conditions" at init?

**Comment by zebzhao** [comment]
Yes. Will add a better error message, for future.
