### ISSUE TITLE
How do you dynamically change the fields items?

### ISSUE THREAD

**Issue by tosehee75** [zebzhao/Angular-QueryBuilder#53]
I have an unique requirement where the field is not a static. In fact, it's driven off of the entity it selects.

Assume I have three parameters (objects): Order, Line, Container. Each of these object has many fields which includes a related entity to another object.

Order contains many lines, and container (box) can include many lines. In short, it's one to many in between. 

From Container, I can reference the line, and from line, I can reference order.

To build a query condition such as below, I need some sort of dynamic behavior.

container.line.order.type == "Sales Order" (where ".type" is the field of Order).

I almost need a typeahead of real-time option changes based on what the user types.

If the user types only "container", it should display the container's fields only. But if the user selects or types "line" which is the field, but as the foreign/related entity, then it needs to display "Line's" fields.  "Order" is another field off of "Line". so, selecting then should also populate the fields with Order's where The "Type can be selected at final.

Is it possible to implement these sort of requirement?

**Comment by tosehee75** [comment]
Similar, but slightly different question.

For above complex requirement reason, I can't use the these directives as is. However, I want to be able to add rule and rule set. 

How can I ignore *queryOperator and *queryInput and *queryField, so I can replace with my own codes while retaining the add rule / set and remove functionalities intact?

**Comment by zebzhao** [comment]
The examples in the demo folder should help in understanding how to override queryField with a custom component, for example a typeahead component. Then you can override the queryInput to also provide a custom typeahead as well. Not sure if this would suffice for your requirements.

I'm currently working on testing a pull request #20 which would have the option to add another field in front of field for entity. You can probably create use a custom typeahead component for query entity, and a custom component for query field in the next version of the library.

**Comment by tosehee75** [comment]
Ok.

I have done that, and got something done.. Now, I am running into another issue where the saved query isn't displaying correctly.

I am guessing that's because it has a lot of attributes it may not recognize?

`{"condition":"and","rules":[{"field":"id","operator":"=","input":"oh.currentStatus","validField":true,"dataType":"Enumeration","operators":["=","!="],"options":[{"code":"In Progress","value":"In Progress"},{"code":"Picking","value":"Picking"},{"code":"Hold","value":"Hold"},{"code":"Open","value":"Open"},{"code":"Voided","value":"Voided"},{"code":"PARTIAL_RETURN","value":"PARTIAL_RETURN"},{"code":"Refunded","value":"Refunded"},{"code":"AWAITING_SHIPMENT","value":"AWAITING_SHIPMENT"},{"code":"FULL_PAYMENT","value":"FULL_PAYMENT"},{"code":"PARTIAL_PAYMENT","value":"PARTIAL_PAYMENT"},{"code":"AWAITING_DELIVERY","value":"AWAITING_DELIVERY"},{"code":"AWAITING_PICKUP","value":"AWAITING_PICKUP"},{"code":"Needs Attention","value":"Needs Attention"},{"code":"New","value":"New"},{"code":"Canceled","value":"Canceled"},{"code":"Complete","value":"Complete"},{"code":"Returned","value":"Returned"},{"code":"Back Ordered","value":"Back Ordered"},{"code":"Receiving","value":"Receiving"},{"code":"Released","value":"Released"},{"code":"Partial Receipt","value":"Partial Receipt"},{"code":"Planned","value":"Planned"},{"code":"Received","value":"Received"},{"code":"Drop Shipped","value":"Drop Shipped"},{"code":"Draft","value":"Draft"}],"value":"New"},{"field":"id","operator":"=","input":"oh.currentStatus","validField":true,"dataType":"Enumeration","operators":["=","!="],"options":[{"code":"In Progress","value":"In Progress"},{"code":"Picking","value":"Picking"},{"code":"Hold","value":"Hold"},{"code":"Open","value":"Open"},{"code":"Voided","value":"Voided"},{"code":"PARTIAL_RETURN","value":"PARTIAL_RETURN"},{"code":"Refunded","value":"Refunded"},{"code":"AWAITING_SHIPMENT","value":"AWAITING_SHIPMENT"},{"code":"FULL_PAYMENT","value":"FULL_PAYMENT"},{"code":"PARTIAL_PAYMENT","value":"PARTIAL_PAYMENT"},{"code":"AWAITING_DELIVERY","value":"AWAITING_DELIVERY"},{"code":"AWAITING_PICKUP","value":"AWAITING_PICKUP"},{"code":"Needs Attention","value":"Needs Attention"},{"code":"New","value":"New"},{"code":"Canceled","value":"Canceled"},{"code":"Complete","value":"Complete"},{"code":"Returned","value":"Returned"},{"code":"Back Ordered","value":"Back Ordered"},{"code":"Receiving","value":"Receiving"},{"code":"Released","value":"Released"},{"code":"Partial Receipt","value":"Partial Receipt"},{"code":"Planned","value":"Planned"},{"code":"Received","value":"Received"},{"code":"Drop Shipped","value":"Drop Shipped"},{"code":"Draft","value":"Draft"}],"value":"Hold"},{"field":"id","operator":"=","input":"oh.addressValidated","validField":true,"dataType":"Boolean","operators":["=","!="]}]}`

**Comment by tosehee75** [comment]
bump

**Comment by tosehee75** [comment]
bump

**Comment by zebzhao** [comment]
Please post a full example of your code on plunker for me to figure out what you're doing wrong. Looking at your example, the fields of your object does not match the `Rule` and `Ruleset` interface. Additionally, judging from your error you might be deleting the `rules` somewhere in your code.

**Comment by tosehee75** [comment]
Here ist he source codes.

**Comment by tosehee75** [comment]
bump

**Comment by tosehee75** [comment]
bump

**Comment by ameagol** [comment]
I'm facing the same issue. Biggest problem here is fields, instead of array, is an object list. 

` fields:{ { name: {name: 'Name', type: 'string'},
      notes: {name: 'Notes', type: 'textarea'},
      educated: {name: 'College Degree?', type: 'boolean'}}`

 Would be much easy to work with, if it was

`fields: [{ name: {name: 'Name', type: 'string'},
      notes: {name: 'Notes', type: 'textarea'},
      educated: {name: 'College Degree?', type: 'boolean'}
}]`

**Comment by ameagol** [comment]
Fixed doind this

```
setExpressionParam(): FieldMap{
  
      let objList: Field[] = []; 
        arrayexample.parameters.forEach(param => { 
              let x = { name: param.parameterName, type: 'string' }
              if (objList.indexOf(x) === -1) {
                objList.push(x); 
              }  
        }); 

      const arrayToObject = (array) =>
          array.reduce((obj, item) => {
            obj[item.name] = item
            return obj
          }, {})
      
      const fieldMap:FieldMap = arrayToObject(objList)

      console.log(objList);
      console.log(fieldMap); 
      return fieldMap; ;
    
  } 
```
