### ISSUE TITLE
Angular 5 support

### ISSUE THREAD

**Issue by jacopolanzoni** [zebzhao/Angular-QueryBuilder#55]
You claim your package is Angular 4+, but if I user Angular 5 I get warnings:

npm WARN angular2-query-builder@0.2.5 requires a peer of @angular/common@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN angular2-query-builder@0.2.5 requires a peer of @angular/core@^4.0.0 but none is installed. You must install peer dependencies yourself.

Can you please make your package Angular 5 compatible?

**Comment by zebzhao** [comment]
Thanks for the bug report. Will fix the warnings next release.
