### ISSUE TITLE
How I can insert a group attribute?

### ISSUE THREAD

**Issue by demianMi** [zebzhao/Angular-QueryBuilder#56]
Hello,
how I can insert a dropdown with group attribute?
I need to divide graphicaly options like <optgroup> but i won't create a custom element because i like default select.

example: [optgroup](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/optgroup) 
my datas: 
`groupAttributes : [{
 label: group1,
 items:[ { id: '1', label: "Total", type: "number"} ]
 },
 label: group2,
 items:[ { id: '2', label: "Other", type: "string"} ]
]`

Thanks in advance.

**Comment by zebzhao** [comment]
Please see if the new entity mode in 0.3.0 suit your needs. You can use a custom component with the default theming to try and support `optgroup`. However, I currently have no plans to support this feature right now as I do not see a way to implement this cleanly. Pull requests are welcomed though, if someone can do it while still supporting the various other use cases of the library.
