### ISSUE TITLE
Hide add rule button

### ISSUE THREAD

**Issue by Abdullah0991** [zebzhao/Angular-QueryBuilder#57]
Hi, (using latest version 0.2.5 and Angular 5)

Is there any way to hide the add rule button? like the 'allowRuleset' option?
I want to set the query rules and let the user to only fill in the values of the fields!

If there is any way please tell me how ASAP.

Regards

**Comment by zebzhao** [comment]
You can override the structural directives as another way to preven adding and removing rules. See this plunkr: https://plnkr.co/edit/VrvdWXUvXn2O7F9GLT7C?p=preview

**Comment by Abdullah0991** [comment]
Awesome !! Thank you @zebzhao
