### ISSUE TITLE
Watch for input changes

### ISSUE THREAD

**Issue by sorcamarian** [zebzhao/Angular-QueryBuilder#6]
Is it possible to get notified once a change on a input is performed?

**Comment by zebzhao** [comment]
Marking this as an enhancement for next release.

**Comment by zebzhao** [comment]
4326249395c453e1fe4aad52cb8e8f543cec390b

**Comment by zebzhao** [comment]
Since release 0.2.0 if you need to watch for input changes, use a custom input component and add change listeners to it.
