### ISSUE TITLE
Disabled (read only) state for the component

### ISSUE THREAD

**Issue by mchapliuk** [zebzhao/Angular-QueryBuilder#61]
Hi @zebzhao 

The docs stay about 'disabled' property: https://zebzhao.github.io/Angular-QueryBuilder/components/QueryBuilderComponent.html#disabled

How can I properly use it? When I pass [disabled]="true" - nothing changes.
Is that implemented?

**Comment by zebzhao** [comment]
No it's not implemented currently.
