### ISSUE TITLE
How would it get rule type in query output

### ISSUE THREAD

**Issue by tonycngo** [zebzhao/Angular-QueryBuilder#62]
in the config, I can see rule type as 'number', 'string', etc...  How come in the query output does not have type?  

{
  "condition": "and",
  "rules": [
    {
      "field": "age",
      "operator": ">",
      "entity": "what",
      "value": [
        32
      ]
    }
  ]
}

**Comment by zebzhao** [comment]
The type is metadata about the fields, not the actual data that will be modified by the query builder.
