### ISSUE TITLE
When trying to do simple custom query input.  I get a undefined value in the text area.

### ISSUE THREAD

**Issue by tonycngo** [zebzhao/Angular-QueryBuilder#63]
Why I get an undefined in the textarea in the query input?  the example shows to user [(ngModel)] but it does not allow ngModel.

<query-builder #qbuilder class="margin30" [(value)]='query' [config]='config'>
  <ng-container *queryInput="let rule; type: 'textarea'">
    <textarea class="form-control" **[(value)]="rule.value"**
          placeholder="Custom Textarea"></textarea>
  </ng-container>
</query-builder>

**Comment by tonycngo** [comment]
How would i get the value off the fileupload from queryinput?

  public config: QueryBuilderConfig = {
    fields: {
      age: {name: 'Age', type: 'number'},
      gender: {
        name: 'Gender',
        type: 'category',
        options: [
          {name: 'Male', value: 'm'},
          {name: 'Female', value: 'f'}
        ]
      },
      name: {name: 'Name', type: 'string', entity: 'file'},
      notes: {name: 'Notes', type: 'file', operators: ['=']},
      educated: {name: 'College Degree?', type: 'boolean'},
      birthday: {name: 'Birthday', type: 'date', operators: ['=', '<=', '>'],
        defaultValue: (() => new Date())
      },
      school: {name: 'School', type: 'string', nullable: true},
      occupation: {
        name: 'Occupation',
        type: 'category',
        options: [
          {name: 'Student', value: 'student'},
          {name: 'Teacher', value: 'teacher'},
          {name: 'Unemployed', value: 'unemployed'},
          {name: 'Scientist', value: 'scientist'}
        ]
      }
    }
  };

<query-builder #qbuilder class="margin30" [(value)]='query' [config]='config'>
  <ng-container *queryInput="let rule; type: 'file'">
    <input type="file" [(value)]="rule.value.target.filename" />
  </ng-container>
</query-builder>

**Comment by zebzhao** [comment]
I believe these are Angular questions. A common mistake is not importing FormModule when trying to use [(ngModel)]: https://github.com/ng-select/ng-select/issues/187

Here is one solution for file uploads using (change) event handler. You can register the value of the input on the rule in the function handle: https://stackoverflow.com/questions/47936183/angular-5-file-upload

Good luck with what you're trying to do!

**Comment by tonycngo** [comment]
Is there a way to trigger the queryinput template based on what type of operator selected?  Let say I created a rule with type as string and operator as 'infile' which cause a template override the textbox with file upload box?
Much help is appreciated.

**Comment by zebzhao** [comment]
Please see this plunkr: https://plnkr.co/edit/WvU8Znd44W4iodEqUgn6?p=preview

**Comment by tonycngo** [comment]
Exactly what I am looking for.  Thanks a bunch!
