### ISSUE TITLE
How to add/alter or internationalize AND/OR in RuleSet?

### ISSUE THREAD

**Issue by Zordid** [zebzhao/Angular-QueryBuilder#64]
First of all, we need to i18n the hardcoded AND / OR boolean operators of the switch group (aka RuleSet?) to read "Und" and "Oder" in German.

But then: are those two options hardcoded or can they be extended? Like if I would like to offer Xor additionally?

Can anybody assist in getting this accomplished?

Thanks!

**Comment by zebzhao** [comment]
Use the querySwitchGroup directive as shown in the demo: https://github.com/zebzhao/Angular-QueryBuilder/blob/master/demo/src/app/app.component.ts

**Comment by poojan1gajera** [comment]
Can you elaborate on this ? I am fairly new to angular and can not add an extra option for "NOT"

**Comment by poojan1gajera** [comment]
> First of all, we need to i18n the hardcoded AND / OR boolean operators of the switch group (aka RuleSet?) to read "Und" and "Oder" in German.
> 
> But then: are those two options hardcoded or can they be extended? Like if I would like to offer Xor additionally?
> 
> Can anybody assist in getting this accomplished?
> 
> Thanks!

@Zordid Did you figure out how to do it ?
I want to add a button for "NOT" here.
