### ISSUE TITLE
Test object against constructed query

### ISSUE THREAD

**Issue by khanyuriy** [zebzhao/Angular-QueryBuilder#68]
Hi! 
Is there any way  to test my javascript collection of objects against a built query?

I found converting query to sql, to mongo plugins. Documentation said that there is parsers for backends. But where is the parser for frontend? How to test vanilla javascript array of objects?

Thanks!

**Comment by zebzhao** [comment]
Correct me if I'm wrong, do you want to convert the built query back to objects? The library is just a simple UI component and does not handle any logic for converting to queries or back.

**Comment by khanyuriy** [comment]
Hi! I want method, that can check if object match query, built with this
builder.

IsMatch(query, object) = true/false;
arrayOfObjects.map(obj => IsMatch(query, obj)) = array of matched objects.


пт, 5 окт. 2018 г., 3:48 zebzhao <notifications@github.com>:

**Comment by zebzhao** [comment]
I think this feature is beyond the scope of this library. Not everyone using this library will find this feature useful if they are querying a database instead of doing object matching in the browser. If anyone thinks otherwise please reopen this issue.

**Comment by Delink-D** [comment]
This would be useful to us, a method to parse an object by passing in the object and the rules. Similar to  [jsonlogic.apply](http://jsonlogic.com/)
