### ISSUE TITLE
Error when switching from single selection to multiple selection mode

### ISSUE THREAD

**Issue by kwkelly** [zebzhao/Angular-QueryBuilder#69]
When switching a field with type 'category' from single selection to multiple selection, the query builder throws an error if an item was selected in single selection mode. It appears to be related to material:

```ERROR Error: "Uncaught (in promise): Error: Value must be an array in multiple-selection mode.```

To replicate, go to the [demo application](https://zebzhao.github.io/Angular-QueryBuilder/demo/), set 'Occupation' to the '=' operator, make a selection, and then switch to the 'in' operator.

**Comment by zebzhao** [comment]
Fixed in 0.4.0.
