### ISSUE TITLE
TypeError: _v.context.changeField is not a function

### ISSUE THREAD

**Issue by rajanalwan** [zebzhao/Angular-QueryBuilder#72]
I was trying to use the custom message for empty ruleset and thus I shifted from v0.2.5 to v0.3.3. I get this error after I shifted. I am not able to change the operators for a field when I change the field itself.

```
ERROR TypeError: _v.context.changeField is not a function
    at Object.eval [as handleEvent] (TestComponent.html:99)
    at handleEvent (core.js:11115)
    at callWithDebugContext (core.js:12212)
    at Object.debugHandleEvent [as handleEvent] (core.js:11915)
    at dispatchEvent (core.js:8582)
    at core.js:10052
    at SafeSubscriber.schedulerFn [as _next] (core.js:3733)
    at 
```

**Comment by zebzhao** [comment]
Please see change log https://github.com/zebzhao/Angular-QueryBuilder/blob/master/CHANGELOG.md#version-030

The `changeField` callback has been renamed to `onChange`.

**Comment by pcurrivan** [comment]
The Angular Material example in the readme still uses 'changeField'.

**Comment by RobinZhao00** [comment]
u can try to bind getToal to this component , since u can only call functions in template which are declared in it
