### ISSUE TITLE
Add new rule by default when adding ruleset

### ISSUE THREAD

**Issue by JeramieHallyburton** [zebzhao/Angular-QueryBuilder#75]
When adding a new ruleset, there is a warning message shown by default. Is there a way to start with a new rule inserted instead of having users perform another click to add rule?

![image](https://user-images.githubusercontent.com/26013059/49254329-f9029300-f3f6-11e8-959d-e4286c94cd38.png)

Thanks!

**Comment by zebzhao** [comment]
Yes you can actually, if you read the code for the component, you can see can override addRuleSet to create an object and set a copy of the array as a new rules property.

**Comment by JeramieHallyburton** [comment]
That is great, this works perfectly. Very powerful component you have created. Thanks for this!

**Comment by sarahmarciano1** [comment]
Hi, 
Thank you for your awesome component
can you provide an example of how you are doing this please?

**Comment by iKrishnaSahu** [comment]
> Hi,
> Thank you for your awesome component
> can you provide an example of how you are doing this please?

@sarahmarciano1 
I think I am late but still posting solution for others.

Inside you template 

```html
<ng-container *queryButtonGroup="let ruleset; let addRule=addRule; let addRuleSet=addRuleSet; 
  let removeRuleSet=removeRuleSet">
  <button type="button" mat-icon-button *ngIf="removeRuleSet" (click)="removeRuleSetCustom(ruleset)">
    <mat-icon>remove_circle_outline</mat-icon>
  </button>
</ng-container>
```

Inside you ts file

```ts
removeRuleSetCustom(parentRuleSet: RuleSet) {
  parantRuleSet.rules.push({ condition: 'all', rules: [{ field: 'name', operator: 'equals', value: 'John' }] });
}
```
