### ISSUE TITLE
[Bug] Changing between entities doesn't reset rule field values when category type is used

### ISSUE THREAD

**Issue by Juhadinitus** [zebzhao/Angular-QueryBuilder#79]
Steps to reproduce within demo

1. Create entity categories
2. Add Fields to categories, populate their values, the fields must use category
3. When using entity mode inspect the field values for a category field, they should appear correctly
4. Change from one entity to another

Result:
1. Inspect the values again, the values are taken from the previous entity field's options 
2. Inspect JSON: rule's entity has changed but the field has remained from the previous

Related PR
#78

**Comment by Yosr-Ch** [comment]
Hi!
I need this fix, what can I do?
Thanks

**Comment by vigneshbarani24** [comment]
Yeah, I am facing the same issue. how can i get through this ?
