### ISSUE TITLE
SQL Support 

### ISSUE THREAD

**Issue by nazrdogan** [zebzhao/Angular-QueryBuilder#8]
How can convert json to sql ?

**Comment by zebzhao** [comment]
You can convert the JSON to SQL on the server side. The query builder allows for custom operators and types, so how you convert to SQL is up to you.

**Comment by mannava** [comment]
can you paste sample code how it convert JSON to SQL
I tried at server side using JSON-SQL library. But query-builder generates JSON in different format.
var jsonSql = require('json-sql')();

var sql = jsonSql.build({
        type: 'select',
        table: 'rxtrac.master_details',
        condition: {name: 'Max', id: 6}
    });
    console.log(sql);

**Comment by mannava** [comment]
I could not find how to convert JSON to SQL

"{"condition":"and","rules":[{"field":"EI_TIMESTAMP","operator":"=","value":"2018-04-04"},{"field":"EI_TRXN_TYPE","operator":"=","value":"sap"}]}"

top json, I want to convert to SQL

**Comment by elisabetb** [comment]
Hi, I have the same issue here. Is there any way I can do it?
