### ISSUE TITLE
[Feature] Persist Value When Changing Field

### ISSUE THREAD

**Issue by pcurrivan** [zebzhao/Angular-QueryBuilder#94]
Give the option to have input values not be reset when the field is changed.
Would you be open to a PR adding this feature?

**Comment by zebzhao** [comment]
This would only work for string/number input no? When would this be applicable in a real-world scenario?

**Comment by pcurrivan** [comment]
In my case all fields are type 'string' and some fields are similar so the user may not appreciate the value being cleared when trying different fields.  I was thinking of adding a way to specify which field types should persist values.  Something like this?

|Name|Type|Required|Default|Description|
|:--- |:--- |:--- |:--- |:--- |
|`persistValueOnFieldChange`|`boolean`|Optional|`false`| If `true`, when a field changes for configured persistValueTypes, only reset the value if the field's type changes. |
|`persistValueTypes`|`object`|Optional|| By default, if persistValueOnFieldChange is `true`, values will be persisted for the following types: string, number, time, date, boolean. Use this option to override or add new persistable types. |

**Comment by zebzhao** [comment]
I'm thinking of something more flexible. Would something like `coerceValueForField(fieldValue: string, value: any, rule: Rule): any` work for you? The default behavior can be preserving number -> number and string -> string, and time -> time, date -> date, boolean -> boolean. If more advanced behavior is required like string -> time, or time -> date, users can override the function using the config object. This is similar to the behavior provided by `coerceValueForOperator(operator: string, value: any, rule: Rule)`.

**Comment by pcurrivan** [comment]
How about this?

|Name|Type|Required|Default|Description|
|:--- |:--- |:--- |:--- |:--- |
|`fieldChangeValueStrategy`|` 'default' \| 'persist' \| 'custom'`|Optional|`'default'`|Configures how the value is determined when a rule's field changes. If `'default'`, the value will reset to the default value of the new field if it exists. If `'persist'`, the value will be retained if the field's type does not change and is one of: `'string'`, `'number'`, `'time'`, `'date'`, `'boolean'`. If `'custom'`, the value will be calculated using the `calculateFieldChangeValue` function provided in the config object. |
|`config.calculateFieldChangeValue`|`(currentField: Field, nextField: Field, currentValue: any) => any`|Optional|| If fieldChangeValueStrategy is `'custom'`, this is used to calculate the new value when a rule's field changes. |

**Comment by zebzhao** [comment]
Yes, I do not see any problems with this. Just a small detail, but I think specifying `calculateFieldChangeValue` should automatically override the `fieldChangeValueStrategy`, that way when it's specified (which the users definitely intends to modify the field change behavior) there's no need to set an additional value to custom.

**Comment by whitegoat** [comment]
This feature when do you have plan to release.

**Comment by pcurrivan** [comment]
> 
> 
> This feature when do you have plan to release.

I plan to submit a PR within a week or so
