### ISSUE TITLE
[Question]How to create only one set of rule/ruleset buttons?

### ISSUE THREAD

**Issue by sandeesaripalli** [zebzhao/Angular-QueryBuilder#95]
I am trying to have only one set of Rule/Ruleset buttons. I am not able to set the context of buttons when I am trying to add rule to a child. It is always taking the parent context. Any guidance will be helpful. I am trying to set the buttons' context to current rule selection.

**Comment by KevinvanLoon** [comment]
Did you manage to create a solution for this? If so, please let me know. Im facing the same issue.
